version: '3'
services:
  dev:
    image: kviolet:latest
    volumes:
      - /opt/sdk/rk3568:/opt/sdk/rk3568
      - /opt/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf:/opt/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf
      - /opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf:/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf
      - /home/i/.ssh:/home/developer/.ssh
      - /home/i/.gitconfig:/home/developer/.gitconfig
      - ../:/home/developer/workspace
